### ISSUE TITLE
Create "_____ typing..." component

### ISSUE THREAD

**Issue by mihok** [minimalchat/client#15]
Given an active conversation with an Operator
When they begin typing in the minimalchat/mnml-operator-app conversation for the current client
And a `operator:typing` event is recieved by the current client
Then a component on the client is updated to show who is typing (Think, Operator name + 'typing ...')

Bonus if the ... animates? Not sure how that would look or function though

**Comment by broneks** [comment]
I think I can take this on

**Comment by mihok** [comment]
Same as the other issue, we should do this in @teesloane's [Preact version](https://github.com/teesloane/mnml-client-preact)

**Comment by mihok** [comment]
This is done in #34
