### ISSUE TITLE
Create a notification component

### ISSUE THREAD

**Issue by mihok** [minimalchat/client#16]
Given a client with an open chat
When disconnected, or trying to reconnect, or reconnected successfully
Then a notifcation bar is shown in the chat window showing that the client is disconnected/reconnecting/reconnected

**Comment by broneks** [comment]
I think I can take this one on too

**Comment by mihok** [comment]
Rad, just a FYI, ideally we probably should do this in @teesloane's [Preact version](https://github.com/teesloane/mnml-client-preact) to minimize duplication

**Comment by teesloane** [comment]
I believe this can be marked done no? via #27

**Comment by mihok** [comment]
Done via #27 pending #33
