### ISSUE TITLE
Menu-less bar doesn't look super happy

### ISSUE THREAD

**Issue by teesloane** [minimalchat/client#38]
# Screenshot

![image](https://user-images.githubusercontent.com/12987958/30669463-75a5cda4-9e2c-11e7-94c9-931302125103.png)

![image](https://user-images.githubusercontent.com/12987958/30669526-ab22745a-9e2c-11e7-8c58-2c2364e6fd22.png)

**Comment by agmcleod** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/113275/30669785-98436ea6-9e2d-11e7-87e8-c9668c040067.png">

**Comment by mihok** [comment]
Closing and reopening on proper repo https://github.com/minimalchat/operator-app/issues/73
